application: usi-help-system
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /style.css
  static_files: static/style.css
  upload: static/style.css

- url: /Index.js
  static_files: static/Index.js
  upload: static/Index.js

- url: .*
  script: main.app

- url: /static
  static_dir: static

libraries:
- name: webapp2
  version: "2.5.2"
